print('Ingrese el primer número: ')
firstNumber=input()
print('Ingrese el segundo número: ')
secondNumber=input()
print('La suma de {firstNumber} y {secondNumber} es {sum}'.format(firstNumber=firstNumber,secondNumber=secondNumber,sum=int(firstNumber)+ int(secondNumber)))